### ISSUE TITLE
Add `io` requirement in README

### ISSUE THREAD

**Issue by PoslavskySV** [gap-system/genss#4]
It seems that `genss` also requires `io` package, which is not installed by default. I think it should be added to README that in addition to `orb`, `io` package should be installed as well.

**Comment by alex-konovalov** [comment]
Thank you - indeed, the PackageInfo.g file states both `IO` and `orb` packages as required.

**Comment by PoslavskySV** [comment]
Thank you! Sorry, I'm new in GAP and I looked only in README file.

**Comment by alex-konovalov** [comment]
Yes, I meant to say that you're right - `PackageInfo.g` is supposed to be read by the package loading routines (or to automatically generate content of http://www.gap-system.org/Packages/genss.html), but not so often to be read by humans; thus, your suggestion of course makes sense.

**Comment by fingolfin** [comment]
Thank you for the report, and sorry for taking so long to respond.

I changed the README accordingly, so it'll be fine in the next release
